### ISSUE TITLE
Feature required: Playlist Downloading

### ISSUE THREAD

**Issue by Effect-Wei** [ThetaRain/NeteaseCloudMusic#1]
In most cases, users prefer to simply provide the PlaylistID and let the program do other work, instead of manually copying the SongID of the entire playlist.

**Comment by ThetaRain** [comment]
The problem is that Netease only displays 10 songs of a playlist without signing in,  and no private playlist for the same reason. To get a web page with cookie won't be easy before doing research for login part of Netease.
If selenium webdriver can extract SongIDs from a web page with sighing in, this feature will be added in the next version.
